spring:
  application:
    name: asianwallet-task
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true

#==================== 日志  ============================
logging:
  config: classpath:logback.xml
